### ISSUE TITLE
Wayscript isn't free anymore?

### ISSUE THREAD

**Issue by SleepingPanda** [am-steph/wayscript-login-helper#3]
I'd noticed the check-ins hadn't occured for the past couple days so I finally logged in to see what's wrong and saw this red notification at the top of the site: "Your free trial of WayScript has expired. Please upgrade to a paid plan to continue. Upgrade your plan now"

I definitely did not sign up for a "free trial" and went to check their plans and didn't see anything about a trial either. There's still the 3 tiers listed but below the Free tier there's red text "Your trial has ended".

Is this happening to anyone else?

**Comment by Stephanos23** [comment]
Wayscript has sent out multiple emails regarding their decision to end free tier months ago. You signed up for a free account which at the time was continously free while they were in development. These free accounts are now a free trial which you would have to pay for afterwards to continue using the service.

**Comment by am-steph** [comment]
Wayscript isn't free anymore since they aren't profiting from people freeloading off their services, alternatives would be using some other cloud service like AWS/GCP/Azure on their free tiers to run the python script
